os: windows
language: cpp
cache:
  directories:
    - $HOME/AppData/Local/Temp/chocolatey
env:
  - CLI_VERSION=latest
before_script:
  - choco install maven -y --no-progress
matrix:
  include:
    - jdk: oraclejdk11
      # See https://github.com/travis-ci/travis-ci/issues/8667
      install: true
      script:
        - mvn clean jacoco:prepare-agent install jacoco:report
      after_success:
        - bash <(curl -s https://codecov.io/bash)
#      deploy:
#        - provider: bintray
#          file: bintray_info_maven.JSON
#          user: incplusplus
#          key: "$bintray_key"
#          skip_cleanup: true
#          on:
#            repo: IncPlusPlus/bigtoolbox-network
#            branch: master
